Service setup
mcharrod/fast_food_backend pull request #1
Opened 2022-06-02 02:24 UTC by mcharrod

I finally got the service reaching our first endpoint yayayaya

2022-06-03 14:02 UTC, Reuben-Davison requested changes
I think we can merge this after the gem file is cleaned up. The pre made comments in the RSpec Config could also be removed to make the code a bit cleaner

2022-06-03 14:02 UTC, Reuben-Davison commented on Gemfile
> +gem 'faraday'
Lets remove one of the faradays

2022-06-03 14:02 UTC, Reuben-Davison commented on Gemfile
> +  gem 'factory_bot'
lets remove factory-bot because we needed factory_bot_rails

2022-06-04 20:59 UTC, alexGrandolph commented
Katy could you add this line to the RecipesController

```class Api::V1::RecipesController < ApplicationController
  skip_before_action :verify_authenticity_token```
  
  For some reason its needed when trying to call the api from the front end

2022-06-05 07:00 UTC, merged